version: '3.8'
services:
  database:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    volumes:
      - redis-data:/data

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  collector:
    build:
      context: ./backend
      dockerfile: Dockerfile-collector
    environment:
      - REDIS_URL=${REDIS_URL}
      - COLLECTOR_PORT=${COLLECTOR_PORT}
      - FRONT_PORT=${FRONT_PORT}
    ports:
      - "${COLLECTOR_PORT}:${COLLECTOR_PORT}"
    depends_on:
      - database
  processor:
    build:
      context: ./backend
      dockerfile: Dockerfile-proc
    environment:
      - REDIS_URL=${REDIS_URL}
      - PROCESSOR_PORT=${PROCESSOR_PORT}
    ports:
      - "${PROCESSOR_PORT}:${PROCESSOR_PORT}"
    depends_on:
      - database
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - PUBLIC_COLLECTOR_PORT=${COLLECTOR_PORT}
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - collector
volumes:
  redis-data:
  redis-insight: